const PrivacyPolicy = () => {
    return (
        <div className='max-w-7xl mb-10 mx-auto max-2xl:mx-5 mt-5'>
            <div className="style-0">
                <p className="text-sm text-gray-400 mb-5">The Direct Promotions Privacy Policy explains how personal information about you is collected, used and disclosed by A&A Phone Solutions, LLC (doing business as Direct Promotions) ("Direct Promotions", "we" or "us") when you access and use Direct Promotions's websites, applications and services that link to this Privacy Policy (collectively, the "Services"), contact Gazelle’s customer service team, engage with Direct Promotions on social media or otherwise interact with Direct Promotions. This Privacy Policy does not apply to any other kiosks, websites or other online or mobile services or applications of A&A Phone Solutions, LLC or its subsidiaries or affiliates that do not link to this policy.
                </p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Personal Information Collection</h4>

                <p className="text-sm text-gray-400 mb-5">We collect information you provide directly to us. For example, we collect information about you when you: (a) transact with us (e.g., sell, donate, ship, or purchase a device or offer to do any of the foregoing), (b) register to open an account with Direct Promotions, (c) sign up for special offers; (d) contact us for help or customer support; (e) complete a survey; (f) post content or provide us with feedback; or (g) enter promotions or sweepstakes. The types of personal information we may collect include your name, phone number, address, email address, zip code, payment information, demographic information, and education information. If you enter a contest or sweepstakes, we may collect your social security number. In some cases, we may also collect information you provide about others, such as when you purchase a gift card for someone and request that we deliver it electronically or if you decide to purchase and ship products to someone else. We will use this information to fulfill your requests and will not send communications to your contacts unrelated to your requests unless they separately consent to receive communications from us or otherwise engage with us. </p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Use of Personal Information</h4>

                <p className="text-sm text-gray-400 mb-5">We primarily use your personal information to provide the Services to you. We also use your personal information to: (a) send you marketing messages and to customize, measure, and analyze the advertising and content you see; (b) fulfill any transactions, including your requests for products and services and send you related information (including by text message), such as confirmations, receipts, invoices, updated offers, and customer experience surveys; (c) personalize and improve your experience on our Services and offerings to you; (d) monitor and analyze trends, usage and activities in connection with our Services, including conducting research (for example, we may contact you for feedback about our products); (e) respond to your comments and questions and provide you with customer support; (f) send you technical notices, security alerts and administration messages, including providing you with updates and notices about the Services, our Privacy Policy and terms and conditions; (g) communicate with you regarding the Services; (h) communicate with you about products, services and events and provide you with new, information and offers from us, our affiliates and from third parties that may be of interest to you; (i) facilitate contests, sweepstakes, and promotions and process and deliver entries and rewards; (j) detect, investigate and prevent fraud, security incidents and other malicious, deceptive or illegal activity and, where necessary, to protect the rights and property of ourselves and third parties; (k) comply with our legal, regulatory and financial obligations; (l) diagnose problems with our servers and software, including debugging to identify and repair errors in our Services; and (m) carry out any other purpose described to you at the time the information was collected.</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Cookies and Other Tracking Technologies</h4>

                <p className="text-sm text-gray-400 mb-5">We use various technologies to collect information, and this may include placing cookies on your computer. A "cookie" is a small file containing a string of characters that is sent to your computer and stored on your hard drive when you visit a website; many major Web services use them, including to provide useful features for their users. . Most browsers are initially set up to accept cookies. You can usually reset or adjust your browser to remove or refuse all cookies or to indicate when a cookie is being sent; however, if you reject or remove cookies, it could affect the availability and functionality of the Services. Direct Promotions uses cookies for the following general purposes: (a) to provide you with personalized content and messaging and to provide and improve our Services and your experience; (b) to display the most appropriate advertisements, based on your interests and activity on our web site; and (c) to help us analyze and estimate our traffic and use of features on the Services; and (d) to keep track of items you put into your shopping cart and to alert you if you leave items in your shopping cart.</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Third-Party Advertising and Analytics</h4>

                <p className="text-sm text-gray-400 mb-5">We may use other companies under agreements with us to serve advertisements and provide analytics services on our behalf. These companies may collect and use information about your visits to the Services and other Web sites (including your IP address, web browser, pages viewed, time spent on pages, links clicked and conversion information). This information may be used by Direct Promotions and others to, among other things, provide advertisements about goods and services likely to be of greater interest to you and to better understand your online activities. These companies typically use cookies, web beacons and/or pixel tags to collect this information.</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Personal Information Sharing and Disclosure</h4>

                <p className="text-sm text-gray-400 mb-5">Direct Promotions does not share personal information about you with other people or third parties except when we have your permission or at your instruction, or under the following circumstances:&nbsp;</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Links to Third Party Sites</h4>

                <p className="text-sm text-gray-400 mb-5">The sites displayed as search results or linked to by the Services are developed by people over whom Direct Promotions exercises no control. These other sites may place their own cookies on your computer, collect data or solicit personal information. We may present links in a format that enables us to understand whether they have been followed. We use this information to understand and improve the quality of Direct Promotions's search technology.&nbsp;</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Social Media Plug-ins</h4>

                <p className="text-sm text-gray-400 mb-5">Social media plug-ins of social networks such as Facebook, Twitter, LinkedIn, Yahoo, Windows and Google plus (among others) are integrated on Direct Promotions's website. Where Direct Promotions sites contain a plug-in to a social network, these are clearly marked (e.g. with a Facebook button). If you chose to click on one of these buttons or links, your browser connects directly to the servers of the relevant social network. The social network directly transmits the content of the plugin to your browser. If you are registered on the relevant social network and logged into your respective account the social network receives the information that the web page was used by you. If you interact with a social network plug-in (e.g. you press the Facebook "Like" feature, the Twitter "Tweet this" feature and Google plus "1+" button or equivalent) or drop a comment on the appropriate web page, the corresponding information is directly transmitted to the relevant social network from your browser. If you are not registered with the social network or you are logged out before you visit Direct Promotions's website, there is the possibility that at least your IP address will be submitted to and stored by the social network. If you interact with us through a social media platform, plug-in etc. then you may be permitting us to have on-going access to some limited information from your social network profile (such as name, email address, photo, gender, location, the people/sites you follow etc.). If you do not want the social network to collect the information about you described above, or to share it with Direct Promotions and other third parties, please review the privacy policy of the relevant social network and/or log out of the relevant social network before you visit Direct Promotions's site. As with other sites, you may be able delete any existing cookies placed on your computer by the social network via your browser.</p>
           
                <h4 className="text-xl max-md:text-lg text-black mb-2">Third Parties</h4>

                <p className="text-sm text-gray-400 mb-5">Direct Promotions does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. We encourage you to ask questions before you disclose your personal information to others. For more information about each such third party, please refer to the third party's privacy policy.</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Changes to this Privacy Policy</h4>

                <p className="text-sm text-gray-400 mb-5">We may amend this Privacy Policy at any time by posting the amended terms on this site. We will notify you of such changes by revising the date at the top of the policy and in some cases, we may provide you with additional notice to the primary email address specified in your Direct Promotions account or by placing a notice on our site.&nbsp;</p>

                <h4 className="text-xl max-md:text-lg text-black mb-2">Children</h4>

                <p className="text-sm text-gray-400 mb-5">Direct Promotions is intended for general audiences. Direct Promotions does not knowingly collect or maintain information from users under 13, and no part of the Services are targeted to attract anyone under 13.</p>
            </div>
        </div>
    )
}

export default PrivacyPolicy