const Terms = () => {
  return (
    <div className="max-w-7xl my-10 mx-auto max-2xl:mx-5">
      <h1 className="max-sm:text-lg max-md:text-2xl max-lg:text-4xl text-5xl font-bold text-center mb-10">
        Terms & <span className="text-[#FB6D11]">Conditions</span>
      </h1>
      <p className="text-sm text-gray-400 mb-5">Updated at 2022-05-01</p>
      <h1 className="max-sm:text-lg text-2xl  font-bold text-center mb-5 text-[#FB6D11]">
        Disclaimer
      </h1>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Definitions and key terms
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        To help explain things as clearly as possible in this Disclaimer, every
        time any of these terms are referenced, are strictly defined as:
        <br />
        <span> -Cookie</span> : a small amount of data generated by a website
        and saved by your web browser. It is used to identify your browser,
        provide analytics, remember information about you such as your language
        preference or login information.
        <br />
        <span> -Company</span>: when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Direct Promotion that is responsible for your
        information under this Disclaimer. -Service: refers to the service
        provided by Direct Promotion as described in the relative terms (if
        available) and on this platform.
        <br />
        <span> -Website</span>: Direct Promotion’s&quot; site, which can be
        accessed via this URL: https://www.directpromotion.online/ -You: a
        person or entity that is registered with Direct Promotion to use the
        Services.
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Limited liability
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion endeavors to update and/or supplement the content of
        the website on a regular basis. Despite our care and attention, content
        may be incomplete and/or incorrect. The materials offered on the website
        are offered without any form of guarantee or claim to their correctness.
        These materials can be changed at any time without prior notice from
        Direct Promotion. Particularly, all prices on the website are stated
        subject to typing and programming errors. No liability is assumed for
        the implications of such errors. No agreement is concluded based on such
        errors. Direct Promotion shall not bear any liability for hyperlinks to
        websites or services of third parties included on the website. From our
        website, you can visit other websites by following hyperlinks to such
        external sites. While we strive to provide only quality links to useful
        and ethical websites, we have no control over the content and nature of
        these sites. These links to other websites do not imply a recommendation
        for all the content found on these sites. Site owners and content may
        change without notice and may occur before we have the opportunity to
        remove a link that may have gone ‘bad’. Please also be aware that when
        you leave our website, other sites may have different privacy policies
        and terms that are beyond our control. Please be sure to check the
        Privacy Policies of these sites as well as their &quot;Terms of
        Service&quot; before engaging in any business or uploading any
        information.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Links to Other Websites Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        This Disclaimer applies only to the Services. The Services may contain
        links to other websites not operated or controlled by Direct Promotion.
        We are not responsible for the content, accuracy or opinions expressed
        in such websites, and such websites are not investigated, monitored, or
        checked for accuracy or completeness by us. Please remember that when
        you use a link to go from the Services to another website, our Privacy
        Policy is no longer in effect. You’re browsing and interacting on any
        other website, including those that have a link on our platform, is
        subject to that website’s own rules and policies. Third parties may use
        their own cookies or other methods to collect information about you. If
        You click on third-party link, you will be directed to that third
        party&apos;s site. We strongly advise You to review the Privacy Policy
        and Terms of every site You visit. We have no control over and assume no
        responsibility for the content, privacy policies or practices of any
        third-party sites or services.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Errors and Omissions Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion is not responsible for any content, code, or any other
        imprecision. Direct Promotion does not provide warranties or guarantees.
        In no event shall Direct Promotion be liable for any special, direct,
        indirect, consequential, or incidental damages or any damages
        whatsoever, whether in an action of contract, negligence, or another
        tort, arising out of or in connection with the use of the Service or the
        contents of the Service. Direct Promotion reserves the right to make
        additions, deletions, or modifications to the content of the Service at
        any time without prior notice.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        General Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The Direct Promotion Service and its contents are provided &quot;as
        is&quot; and &quot;as available&quot; without any warranty or
        representations of any kind, whether express or implied. Direct
        Promotion is a distributor and not a publisher of the content supplied
        by third parties; as such, Direct Promotion exercises no editorial
        control over such content and makes no warranty or representation as to
        the accuracy, reliability, or currency of any information, content,
        service or merchandise provided through or accessible via the Direct
        Promotion Service. Without limiting the foregoing, Direct Promotion
        specifically disclaims all warranties and representations in any content
        transmitted on or in connection with the Direct Promotion Service or on
        sites that may appear as links on the Direct Promotion Service, or in
        the products provided as a part of, or otherwise in connection with, the
        Direct Promotion Service, including without limitation any warranties of
        merchantability, fitness for a particular purpose or non-infringement of
        third party rights. No oral advice or written information given by
        Direct Promotion or any of its affiliates, employees, officers,
        directors, agents, or the like will create a warranty. Price and
        availability information is subject to change without notice. Without
        limiting the foregoing, Direct Promotion does not warrant that the
        Direct Promotion Service will be uninterrupted, uncorrupted, timely, or
        error-free.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Copyright Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        All intellectual property rights concerning these materials are vested
        in Direct Promotion. Copying, distribution and any other use of these
        materials is not permitted without the written permission of Direct
        Promotion, except and only to the extent otherwise provided in
        regulations of mandatory law (such as the right to quote), unless
        otherwise stated for certain materials.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Affiliate Links Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion has affiliate links and in this section of the
        Disclaimer we will address how we use those affiliate links from other
        websites/companies and products. These “affiliate links” are specific
        URLs that contain the affiliate&apos;s ID or username. In compliance
        with the FTC guidelines, please assume the following about links and
        posts on this site: -Any/all the links on Direct Promotion are affiliate
        links of which we receive a small commission from sales of certain
        items, but the price is the same for you. As Direct Promotion has grown,
        so have costs associated with running and maintaining it, and affiliate
        links are a way we help offset these costs. -If we post an affiliate
        link to a product, it is something that we personally use, support and
        would recommend without an affiliate link. -Unless otherwise noted, all
        reviews are of items we have purchased, and we are not paid or
        compensated in any way.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Health Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The information on this website such as text, graphics, images, and
        other materials created by Direct Promotion or obtained from Direct
        promotion’s&quot; licensors, and other materials contained on Direct
        Promotion (collectively, Contents”) is intended solely for informational
        purposes and may not be used as a substitute for professional advice
        and/or information, as circumstances will vary from person to person.
        You should not act or rely upon this information without seeking
        professional advice. Do not attempt any of the suggested actions,
        solutions, remedies, or instructions found on this website without first
        consulting with a qualified professional. The materials are not intended
        to be, nor do they constitute actionable professional advice.
        Transmissions of this information are not intended to create a
        professional-client relationship between Level Up Enterprises and you.
        The owners, editors, contributors, administrators, and other staff of
        Level Up Enterprises are not qualified professional, and are simply
        aggregating information found online for informational purposes only. If
        you think you may have a medical emergency, call your doctor or 911
        immediately. Direct Promotion does not recommend or endorse any specific
        tests, physicians, products, procedures, opinions, or other information
        that may be mentioned on the website. Reliance on any information
        provided by Direct Promotion, Direct Promotion employees, others
        appearing on the website at the invitation of Direct Promotion, or other
        visitors to the website is solely at your own risk.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Legal Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The materials, any comments or information provided by Direct Promotion
        are for educational purposes only and nothing conveyed or provided
        should be considered legal, accounting or tax advice. You are
        responsible for whatever you may do with the information you obtain from
        Direct Promotion. As such, by visiting and using this website you
        acknowledge and agree that you have been assessed by a qualified law
        expert (i.e your attorney) who has given you consent to take part in any
        legal activity. Please contact your own attorney, accountant or tax
        professional with any specific questions you have related to the
        information provided that are of legal, accounting or tax nature.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Educational Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Any information provided by Direct Promotion is for educational purposes
        only and is not to be interpreted as a recommendation for a specific
        treatment plan, product, or course of action. Direct Promotion is a
        distributor and not a publisher of the content supplied by third
        parties; as such, Direct Promotion exercises no editorial control over
        such content and makes no warranty or representation as to the accuracy,
        reliability or currency of any information or educational content
        provided through or accessible via Direct Promotion. Without limiting
        the foregoing, Direct Promotion specifically disclaims all warranties
        and representations in any content transmitted on or in connection with
        Direct Promotion or on sites that may appear as links on Direct
        Promotion, or in the products provided as a part of, or otherwise in
        connection with, the Direct Promotion. No oral advice or written
        information given by Direct Promotion or any of its affiliates,
        employees, officers, directors, agents, or the like will create a
        warranty.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent</h4>
      <p className="text-sm text-gray-400 mb-5">
        We&apos;ve updated our Disclaimer to provide you with complete
        transparency into what is being set when you visit our site and how
        it&apos;s being used. By using our website, registering an account, or
        making a purchase, you hereby consent to our Disclaimer and agree to its
        terms.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Changes To Our Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Should we update, amend or make any changes to this document so that
        they accurately reflect our Service and policy?. Unless otherwise
        required by law, those changes will be prominently posted here. Then, if
        you continue to use the Service, you will be bound by the updated
        Disclaimer. If you do not want to agree to this or any updated
        Disclaimer, you can delete your account.
      </p>

      <h1 className="max-sm:text-lg text-2xl  font-bold text-center mb-5 text-[#FB6D11]">
        Cookies
      </h1>
      <p className="text-sm text-gray-400 mb-5">
        This Cookie Policy explains how Direct Promotion and its affiliates
        (collectively &quot;Direct Promotion&quot;, &quot;we&quot;,
        &quot;us&quot;, and &quot;ours&quot;), use cookies and similar
        technologies to recognize you when you visit our website, including
        without limitation https://www.directpromotion.online/ and any related
        URLs, mobile or localized versions and related domains/subdomains
        (&quot;Websites&quot;). It explains what these technologies are and why
        we use them, as well as the choices for how to control them.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What is a cookie?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        A cookie is a small text file that is stored on your computer or another
        internet-connected device to identify your browser, provide analytics,
        remember information about you such as your language preference or login
        information. They&apos;re completely safe and can&apos;t be used to run
        programs or deliver viruses to your device.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Why do we use cookies?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We use first party and/or third-party cookies on our website for various
        purposes such as:
        <br />
        <span>
          -To facilitate the operation and functionality of our website.{" "}
        </span>{" "}
        <br />
        <span>
          -To improve your experience of our website and make navigating around
          it quicker and easier.
        </span>{" "}
        <br />
        <span>
          -To allow us to make a bespoke user experience for you and for us to
          understand what is useful or of interest to you.
        </span>{" "}
        <br />
        <span>
          {" "}
          -To analyze how our website is used and how best we can customize it.
        </span>
        <br />
        <span>
          {" "}
          -To identify prospects and personalize marketing and sales
          interactions with them
        </span>
        <br />
        <span>
          -To facilitate the tailoring of online advertising to your interests.
        </span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What type of cookies does Direct Promotion use?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Cookies can either be session cookies or persistent cookies. A session
        cookie expires automatically when you close your browser. A persistent
        cookie will remain until it expires, or you delete your cookies.
        Expiration dates are set in the cookies themselves; some may expire
        after a few minutes while others may expire after multiple years.
        Cookies placed by the website you’re visiting are called “first party
        cookies”. Strictly Necessary cookies are necessary for our website to
        function and cannot be switched off in our systems. They are essential
        to enable you to navigate around the website and use its features. If
        you remove or disable these cookies, we cannot guarantee that you will
        be able to use our website. We use the following types of cookies in our
        website: <br />
        <span>Essential Cookies</span> We use essential cookies to make our
        website work. These cookies are strictly necessary to enable core
        functionality such as security, network management, your cookie
        preferences, and accessibility. Without them, you wouldn&apos;t be able
        to use basic services. You may disable these by changing your browser
        settings, but this may affect how the Websites function. <br />
        <span>Marketing Cookies</span> These account-based marketing cookies
        enable us to identify prospects and personalize sales and marketing
        interactions with them. <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Marketing Cookies
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Most browsers allow you to control cookies through their
        &apos;settings&apos; preferences. However, if you limit the ability of
        websites to set cookies, you may worsen your overall user experience,
        since it will no longer be personalized to you. It may also stop you
        from saving customized settings like login information. Browser
        manufacturers provide help pages relating to cookie management in their
        products. Browser manufacturers provide help pages relating to cookie
        management in their products. Please see below for more information.{" "}
        <br />
        <span>-Google Chrome</span>
        <br />
        <span> -Internet Explorer</span>
        <br />
        <span> -Mozilla Firefox </span>
        <br />
        <span> -Safari (Desktop)</span>
        <br />
        <span> -Safari (Mobile)</span>
        <br />
        <span>-Android Browser</span>
        <br />
        <span>-Opera</span>
        <br />
        <span>-Opera Mobile</span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Blocking and disabling cookies and similar technologies
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Wherever you&apos;re located you may also set your browser to block
        cookies and similar technologies, but this action may block our
        essential cookies and prevent our website from functioning properly, and
        you may not be able to fully utilize all its features and services. You
        should also be aware that you may also lose some saved information
        (e.g., saved login details, site preferences) if you block cookies on
        your browser. Different browsers make different controls available to
        you. Disabling a cookie or category of cookie does not delete the cookie
        from your browser, you will need to do this yourself from within your
        browser, you should visit your browser&apos;s help menu for more
        information.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Changes To Our Cookie Policy
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may change our Service and policies, and we may need to make changes
        to this Cookie Policy so that it accurately reflects our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Cookie
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Cookie Policy. If you do not want to agree to this or any
        updated Cookie Policy, you can delete your account.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent</h4>
      <p className="text-sm text-gray-400 mb-5">
        By using our website, registering an account, or making a purchase, you
        hereby consent to our Cookie Policy and agree to its terms.
      </p>

      <h1 className="max-sm:text-lg text-2xl font-bold text-center mb-5 text-[#FB6D11]">
        Return & <span className="text-[#FB6D11]">Refund </span>Policy
      </h1>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Definitions and key terms
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        To help explain things as clearly as possible in this Return & Refund
        Policy, every time any of these terms are referenced, are strictly
        defined as:
        <br />
        <span> -Company</span> when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Direct Promotion, which is responsible for your
        information under this Return & Refund Policy.
        <br />
        <span> -Customer</span>: refers to the company, organization, or person
        that signs up to use the Direct Promotion Service to manage the
        relationships with your consumers or service users.
        <br />
        <span> -Device</span>: any internet-connected device such as a phone,
        tablet, computer, or any other device that can be used to visit Direct
        Promotion and use the services.
        <br />
        <span> -Service</span>: refers to the service provided by Direct
        Promotion as described in the relative terms (if available) and on this
        platform.
        <br />
        <span> -Website</span>: Direct Promotion’s&quot; site, which can be
        accessed via this URL: https://www.directpromotion.online/
        <br />
        <span> -You</span>: a person or entity that is registered with Direct
        Promotion to use the Services.
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Return & Refund Policy
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Thanks for shopping at Direct Promotion. We appreciate the fact that you
        like to buy the stuff we build. We also want to make sure you have a
        rewarding experience while you’re exploring, evaluating, and purchasing
        our products. As with any shopping experience, there are terms and
        conditions that apply to transactions at Direct Promotion. We’ll be as
        brief as our attorneys will allow. The main thing to remember is that by
        placing an order or making a purchase at Direct Promotion, you agree to
        the terms set forth below along with the Policy. If there’s something
        wrong with what you bought, or if you are not happy with it, you will
        not be able to issue a refund for your item.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Refunds</h4>
      <p className="text-sm text-gray-400 mb-5">
        We at ourselves to serving our customers with the best products. Every
        single product that you choose is thoroughly inspected, checked for
        defects, and packaged with utmost care. We do this to ensure that you
        fall in love with our products. Sadly, there are times when we may not
        have the product(s) that you choose in-stock or may face some issues
        with our inventory and quality check. In such cases, we may have to
        cancel your order. You will be intimated about it in advance so that you
        don&apos;t have to worry unnecessarily about your order. If you have
        purchased via Online payment (not Cash on Delivery), then you will be
        refunded once our team confirms your request. We carry out a thorough
        quality check before processing the ordered item. We take utmost care
        while packing the product. At the same time, we ensure that the packing
        is good such that the items won’t get damaged during transit. Please
        note that Direct Promotion is not liable for damages that are caused to
        the items during transit or transportation. We follow certain policies
        to ensure transparency, efficiency, and quality customer care: <br />
        <span>-We DO NOT allow returns on sold products</span> - online or in
        retail outlets. <br />
        <span>
          -We DO NOT accept returned goods, as we believe that customers should
          get the best quality products.
        </span>{" "}
        <br />
        -Refunds are NOT given for any purchases made - be they online or in a
        retail store. <br />
        <span>-We DO NOT encourage exchanges of our products.</span> <br />
        <span>
          -We DO NOT engage in reselling used products and discourage the same
          because we cannot ensure the best quality products for our customers.
        </span>
        <br />
        For International Orders:
        <span>-We DO NOT support Exchanges or Returns.</span>
        <br />
        <span>
          -If you cancel the order before we process it and dispatch it for
          shipping, a refund can be processed. Orders generally take 1-2 days to
          process before dispatch.
        </span>
        <br />
        <span>
          -Orders already in shipping cannot be returned, canceled, or refunded.
        </span>
        <br />
        <span>
          {" "}
          -If you face any issues, please contact our Support Team immediately.
        </span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent</h4>
      <p className="text-sm text-gray-400 mb-5">
        By using our website, registering an account, or making a purchase, you
        hereby consent to our Return & Refund Policy and agree to its terms.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Changes To Our Return & Refund Policy
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Should we update, amend or make any changes to this document so that
        they accurately reflect our Service and policies? Unless otherwise
        required by law, those changes will be prominently posted here. Then, if
        you continue to use the Service, you will be bound by the updated Return
        & Refund Policy. If you do not want to agree to this or any updated
        Return & Refund Policy, you can delete your account.
      </p>

      <h1 className="max-sm:text-lg text-2xl font-bold text-center mb-5 text-[#FB6D11]">
        Privacy <span className="text-[#FB6D11]">Policy</span>
      </h1>
      <p className="text-sm text-gray-400 mb-5">Updated at 2022-05-01</p>
      <p className="text-sm text-gray-400 mb-5">
        direct promotion (“we,” “our,” or “us”) is committed to protecting your
        privacy. This Privacy Policy explains how your personal information is
        collected, used, and disclosed by direct promotion.
      </p>
      <p className="text-sm text-gray-400 mb-5">
        This Privacy Policy applies to our website, and its associated
        subdomains (collectively, our “Service”) alongside our application,
        direct promotion. By accessing or using our Service, you signify that
        you have read, understood, and agree to our collection, storage, use,
        and disclosure of your personal information as described in this Privacy
        Policy and our Terms of Service.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Definitions and key terms
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, are strictly defined as:
        <br />
        <span>-Cookie</span> : a small amount of data generated by a website and
        saved by your web browser. It is used to identify your browser, provide
        analytics, remember information about you such as your language
        preference or login information.
        <br />
        <span>-Company</span>: when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Direct promotion that is responsible for your
        information under this Privacy Policy.
        <br />
        <span>-Country</span>: where direct promotion or the owners/founders of
        direct promotion are based, in this case, is the USA
        <br />
        <span>-Customer</span>: refers to the company, organization, or person
        that signs up to use the direct promotion Service to manage the
        relationships with your consumers or service users.
        <br />
        <span>-Device</span>: any internet-connected device such as a phone,
        tablet, computer, or any other device that can be used to visit direct
        promotion and use the services.
        <br />
        <span>-IP address</span>: Every device connected to the Internet is
        assigned a number known as an Internet protocol (IP) address. These
        numbers are usually assigned in geographic blocks. An IP address can
        often be used to identify the location from which a device is connecting
        to the Internet.
        <br />
        <span>-Personnel</span>: refers to those individuals who are employed by
        direct promotion or are under contract to perform a service on behalf of
        one of the parties.
        <br />
        <span>-Personal Data</span>: Any information that directly, indirectly,
        or in connection with other information — including a personal
        identification number — allows for the identification or identifiability
        of a natural person.
        <br />
        <span>-Service</span>: refers to the service provided by direct
        promotion as described in the relative terms (if available) and on this
        platform.
        <br />
        <span>-Third-party service</span>: refers to advertisers, contest
        sponsors, promotional and marketing partners, and others who provide our
        content or whose products or services we think may interest you.
        <br />
        <span> -Website</span>: direct promotion’s&quot; site, which can be
        accessed via this URL: https://www.directpromotion.online
        <br />
        <span> -You</span>: a person or entity that is registered with direct
        promotion to use the Services.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What Information Do We Collect?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We collect information from you when you visit our website, register on
        our site, place an order, subscribe to our newsletter, respond to a
        survey or fill out a form.
        <br />
        <span> -Name / Username</span>
        <br />
        <span>-Phone Numbers</span>
        <br />
        <span>-Email Addresses</span>
        <br />
        <span> -Mailing Addresses</span>
        <br />
        <span> -Billing Addresses</span>
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        How Do We Use the Information We Collect?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Any of the information we collect from you may be used in one of the
        following ways:
        <br />
        <span>
          -To personalize your experience (your information helps us to better
          respond to your individual needs){" "}
        </span>
        <br />
        <span>
          {" "}
          -To improve our website (we continually strive to improve our website
          offerings based on the information and feedback we receive from you){" "}
        </span>
        <br />
        <span>
          {" "}
          -To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
        </span>
        <br />
        <span>-To process transactions</span>
        <br />
        <span>
          -To administer a contest, promotion, survey or other site feature
        </span>{" "}
        <br />
        <span> -To send periodic emails</span>
        <br />
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        When does direct promotion use end user information from third parties?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        direct promotion will collect End User Data necessary to provide the
        direct promotion services to our customers. End users may voluntarily
        provide us with information they have made available on social media
        websites. If you provide us with any such information, we may collect
        publicly available information from the social media websites you have
        indicated. You can control how much of your information social media
        websites make public by visiting these websites and changing your
        privacy settings.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        When does direct promotion use customer information from third parties?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We receive some information from third parties when you contact us. For
        example, when you submit your email address to us to show interest in
        becoming a direct promotion customer, we receive information from a
        third party that provides automated fraud detection services to direct
        promotion. We also occasionally collect information that is made
        publicly available on social media websites. You can control how much of
        your information social media websites make public by visiting these
        websites and changing your privacy settings.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Do we share the information we collect with third parties?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may share the information that we collect, both personal and
        non-personal, with third parties such as advertisers, contest sponsors,
        promotional and marketing partners, and others who provide our content
        or whose products or services we think may interest you. We may also
        share it with our current and future affiliated companies and business
        partners, and if we are involved in a merger, asset sale or other
        business reorganization, we may also share or transfer your personal and
        non-personal information to our successors-in-interest. We may engage
        trusted third-party service providers to perform functions and provide
        services to us, such as hosting and maintaining our servers and the
        website, database storage and management, e-mail management, storage
        marketing, credit card processing, customer service, and fulfilling
        orders for products and services you may purchase through the website.
        We will likely share your personal information, and possibly some
        non-personal information, with these third parties to enable them to
        perform these services for us and for you. We may share portions of our
        log file data, including IP addresses, for analytics purposes with third
        parties such as web analytics partners, application developers, and ad
        networks. If your IP address is shared, it may be used to estimate
        general location and other technographics such as connection speed,
        whether you have visited the website in a shared location, and the type
        of device used to visit the website. They may aggregate information
        about our advertising and what you see on the website and then provide
        auditing, research, and reporting for us and our advertisers. We may
        also disclose personal and non-personal information about you to
        government or law enforcement officials or private parties as we, in our
        sole discretion, believe necessary or appropriate in order to respond to
        claims, legal process (including subpoenas), to protect our rights and
        interests or those of a third party, the safety of the public or any
        person, to prevent or stop any illegal, unethical, or legally actionable
        activity, or to otherwise comply with applicable court orders, laws,
        rules, and regulations.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Where and when is information collected from customers and end-users?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct promotion will collect personal information that you submit to
        us. We may also receive personal information about you from third
        parties as described above.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        How Do We Use Your Email Address?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        By submitting your email address on this website, you agree to receive
        emails from us. You can cancel your participation in any of these email
        lists at any time by clicking on the opt-out link or other unsubscribe
        option that is included in the respective email. We only send emails to
        people who have authorized us to contact them, either directly, or
        through a third party. We do not send unsolicited commercial emails,
        because we hate spam as much as you do. By submitting your email
        address, you also agree to allow us to use your email address for
        customer audience targeting on sites like Facebook, where we display
        custom advertising to specific people who have opted-in to receive
        communications from us. Email addresses submitted only through the order
        processing page will be used for the sole purpose of sending you
        information and updates pertaining to your order. If, however, you have
        provided the same email to us through another method, we may use it for
        any of the purposes stated in this Policy. Note: If at any time you
        would like to unsubscribe from receiving future emails, we include
        detailed unsubscribe instructions at the bottom of each email.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        How Long Do We Keep Your Information?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We keep your information only so long as we need it to provide direct
        promotion to you and fulfill the purposes described in this policy. This
        is also the case for anyone that we share your information with and who
        carries out services on our behalf. When we no longer need to use your
        information and there is no need for us to keep it to comply with our
        legal or regulatory obligations, we’ll either remove it from our systems
        or depersonalize it so that we can&apos;t identify you.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        How Do We Protect Your Information?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We implement a variety of security measures to maintain the safety of
        your personal information when you place an order or enter, submit, or
        access your personal information. We offer the use of a secure server.
        All supplied sensitive/credit information is transmitted via Secure
        Socket Layer (SSL) technology and then encrypted into our Payment
        gateway providers database only to be accessible by those authorized
        with special access rights to such systems and are required to keep the
        information confidential. After a transaction, your private information
        (credit cards, social security numbers, financials, etc.) is never kept
        on file. We cannot, however, ensure or warrant the absolute security of
        any information you transmit to direct promotion or guarantee that your
        information on the Service may not be accessed, disclosed, altered, or
        destroyed by a breach of any of our physical, technical, or managerial
        safeguards.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Could my information be transferred to other countries?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        direct promotion is incorporated in the USA. Information collected via
        our website, through direct interactions with you, or from the use of
        our help services may be transferred from time to time to our offices or
        personnel, or to third parties, located throughout the world, and maybe
        viewed and hosted anywhere in the world, including countries that may
        not have laws of general applicability regulating the use and transfer
        of such data. To the fullest extent allowed by applicable law, by using
        any of the above, you voluntarily consent to the trans-border transfer
        and hosting of such information.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Is the information collected through the direct promotion Service
        secure?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We take precautions to protect the security of your information. We have
        physical, electronic, and managerial procedures to help safeguard,
        prevent unauthorized access, maintain data security, and correctly use
        your information. However, neither people nor security systems are
        foolproof, including encryption systems. In addition, people can commit
        intentional crimes, make mistakes, or fail to follow policies.
        Therefore, while we make reasonable efforts to protect your personal
        information, we cannot guarantee its absolute security. If applicable
        law imposes any non-disclaim able duty to protect your personal
        information, you agree that intentional misconduct will be the standard
        used to measure our compliance with that duty.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Can I update or correct my information?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The rights you have to request updates or corrections to the information
        direct promotion collects depend on your relationship with direct
        promotion. Personnel may update or correct their information as detailed
        in our internal company employment policies. Customers have the right to
        request the restriction of certain uses and disclosures of personally
        identifiable information as follows. You can contact us to (1) update or
        correct your personally identifiable information, (2) change your
        preferences with respect to communications and other information you
        receive from us, or (3) delete the personally identifiable information
        maintained about you on our systems (subject to the following
        paragraph), by canceling your account. Such updates, corrections,
        changes, and deletions will have no effect on other information that we
        maintain or information that we have provided to third parties in
        accordance with this Privacy Policy prior to such update, correction,
        change, or deletion. To protect your privacy and security, we may take
        reasonable steps (such as requesting a unique password) to verify your
        identity before granting you profile access or making corrections. You
        are responsible for always maintaining the secrecy of your unique
        password and account information. You should be aware that it is not
        technologically possible to remove each and every record of the
        information you have provided to us from our system. The need to back up
        our systems to protect information from inadvertent loss means that a
        copy of your information may exist in a non-erasable form that will be
        difficult or impossible for us to locate. Promptly after receiving your
        request, all personal information stored in databases we actively use,
        and other readily searchable media will be updated, corrected, changed,
        or deleted, as appropriate, as soon as and to the extent reasonably and
        technically practicable. If you are an end-user and wish to update,
        delete, or receive any information we have about you, you may do so by
        contacting the organization of which you are a customer.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">Personnel</h4>
      <p className="text-sm text-gray-400 mb-5">
        If you are a direct promotion worker or applicant, we collect the
        information you voluntarily provide to us. We use the information
        collected for Human Resources purposes to administer benefits to workers
        and screen applicants. You may contact us to (1) update or correct your
        information, (2) change your preferences with respect to communications
        and other information you receive from us, or (3) receive a record of
        the information we have relating to you. Such updates, corrections,
        changes, and deletions will have no effect on other information that we
        maintain or information that we have provided to third parties in
        accordance with this Privacy Policy prior to such update, correction,
        change, or deletion.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Sale of Business
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We reserve the right to transfer information to a third party in the
        event of a sale, merger or other transfer of all or substantially all of
        the assets of direct promotion or any of its Corporate Affiliates (as
        defined herein), or that portion of direct promotion or any of its
        Corporate Affiliates to which the Service relates, or in the event that
        we discontinue our business or file a petition or have filed against us
        a petition in bankruptcy, reorganization or similar proceeding, provided
        that the third party agrees to adhere to the terms of this Privacy
        Policy.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">Affiliates </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may disclose information (including personal information) about you
        to our Corporate Affiliates. For purposes of this Privacy Policy,
        &quot;Corporate Affiliate&quot; means any person or entity which
        directly or indirectly controls, is controlled by or is under common
        control with direct promotion, whether by ownership or otherwise. Any
        information relating to you that we provide to our Corporate Affiliates
        will be treated by those Corporate Affiliates in accordance with the
        terms of this Privacy Policy.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">Governing Law </h4>
      <p className="text-sm text-gray-400 mb-5">
        This Privacy Policy is governed by the laws of the USA without regard to
        its conflict of laws provision. You consent to the exclusive
        jurisdiction of the courts in connection with any action or dispute
        arising between the parties under or in connection with this Privacy
        Policy except for those individuals who may have rights to make claims
        under Privacy Shield or the Swiss-US framework. The laws of the USA,
        excluding its conflicts of law rules, shall govern this Agreement and
        your use of the website. Your use of the website may also be subject to
        other local, state, national, or international laws. By using a direct
        promotion or contacting us directly, you signify your acceptance of this
        Privacy Policy. If you do not agree to this Privacy Policy, you should
        not engage with our website, or use our services. Continued use of the
        website, direct engagement with us, or following the posting of changes
        to this Privacy Policy that do not significantly affect the use or
        disclosure of your personal information will mean that you accept those
        changes.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent </h4>
      <p className="text-sm text-gray-400 mb-5">
        We&apos;ve updated our Privacy Policy to provide you with complete
        transparency into what is being set when you visit our site and how
        it&apos;s being used. By using our website, registering an account, or
        making a purchase, you hereby consent to our Privacy Policy and agree to
        its terms.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Links to Other Websites{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        This Privacy Policy applies only to the Services. The Services may
        contain links to other websites not operated or controlled by direct
        promotion. We are not responsible for the content, accuracy or opinions
        expressed in such websites, and such websites are not investigated,
        monitored, or checked for accuracy or completeness by us. Please
        remember that when you use a link to go from the Services to another
        website, our Privacy Policy is no longer in effect. You’re browsing and
        interacting on any other website, including those that have a link on
        our platform, is subject to that website’s own rules and policies. Third
        parties may use their own cookies or other methods to collect
        information about you.
      </p>
      <h4 className="text-xl max-md:text-lg text-black mb-2"> Cookies </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct promotion uses &quot;Cookies&quot; to identify the areas of our
        website that you have visited. A cookie is a small piece of data stored
        on your computer or mobile device by your web browser. We use cookies to
        enhance the performance and functionality of our website but are
        non-essential to their use. However, without these cookies, certain
        functionality like videos may become unavailable or you would be
        required to enter your login details every time you visit the website as
        we would not be able to remember that you had logged in previously. Most
        web browsers can be set to disable the use of Cookies. However, if you
        disable Cookies, you may not be able to access functionality on our
        website correctly or at all. We never place Personally Identifiable
        Information in Cookies.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Blocking and disabling cookies and similar technologies{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Wherever you&apos;re located you may also set your browser to block
        cookies and similar technologies, but this action may block our
        essential cookies and prevent our website from functioning properly, and
        you may not be able to fully utilize all its features and services. You
        should also be aware that you may also lose some saved information
        (e.g., saved login details, site preferences) if you block cookies on
        your browser. Different browsers make different controls available to
        you. Disabling a cookie or category of cookie does not delete the cookie
        from your browser, you will need to do this yourself from within your
        browser, you should visit your browser&apos;s help menu for more
        information.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Remarketing Services{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We use remarketing services. What Is Remarketing? In digital marketing,
        remarketing (or retargeting) is the practice of serving ads across the
        internet to people who have already visited your website. It allows your
        company to seem like they&apos;re “following” people around the internet
        by serving ads on the websites and platforms they use most.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Payment Details
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        In respect to any credit card or other payment processing details you
        have provided us with, we commit that this confidential information will
        be stored in the most secure manner possible.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Kids&apos; Privacy{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We do not address anyone under the age of 13. We do not knowingly
        collect personally identifiable information from anyone under the age of
        13. If You are a parent or guardian and You are aware that Your child
        has provided Us with Personal Data, please Contact Us. If We become
        aware that We have collected Personal Data from anyone under the age of
        13 without verification of parental consent, we take steps to remove
        that information from Our servers.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Changes To Our Privacy Policy{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may change our Services and policies, and we may need to make changes
        to this Privacy Policy so that they accurately reflect our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Privacy
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Privacy Policy. If you do not want to agree to this or any
        updated Privacy Policy, you can delete your account.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        {" "}
        Third-Party Services{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may display, include, or make available third-party content
        (including data, information, applications, and other products services)
        or provide links to third-party websites or services (&quot;Third-Party
        Services&quot;). You acknowledge and agree that direct promotion shall
        not be responsible for any Third-Party Services, including their
        accuracy, completeness, timeliness, validity, copyright compliance,
        legality, decency, quality, or any other aspect thereof. Direct
        promotion does not assume and shall not have any liability or
        responsibility to you or any other person or entity for any Third-Party
        Services. Third-Party Services and links thereto are provided solely as
        a convenience to you, and you access and use them entirely at your own
        risk and subject to such third parties’ terms and conditions.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Tracking Technologies
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        <span> -Local Storage</span> <br />
        Local Storage sometimes known as DOM storage provides web apps with
        methods and protocols for storing client-side data. Web storage supports
        persistent data storage, like cookies but with a greatly enhanced
        capacity and no information stored in the HTTP request header.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Information about General Data Protection Regulation (GDPR){" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may be collecting and using information from you if you are from the
        European Economic Area (EEA), and in this section of our Privacy Policy,
        we are going to explain exactly how and why this data is collected, and
        how we maintain this data under protection from being replicated or used
        in the wrong way.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">What is GDPR? </h4>
      <p className="text-sm text-gray-400 mb-5">
        GDPR is an EU-wide privacy and data protection law that regulates how EU
        residents&apos; data is protected by companies and enhances the control
        the EU residents have over their personal data. The GDPR is relevant to
        any globally operating company and not just the EU-based businesses and
        EU residents. Our customers’ data is important irrespective of where
        they are located, which is why we have implemented GDPR controls as our
        baseline standard for all our operations worldwide.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What is personal data?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Any data that relates to an identifiable or identified individual. GDPR
        covers a broad spectrum of information that could be used on its own, or
        in combination with other pieces of information, to identify a person.
        Personal data extends beyond a person’s name or email address. Some
        examples include financial information, political opinions, genetic
        data, biometric data, IP addresses, physical addresses, sexual
        orientation, and ethnicity. The Data Protection Principles include
        requirements such as:
        <span>
          {" "}
          -Personal data collected must be processed in a fair, legal, and
          transparent way and should only be used in a way that a person would
          reasonably expect.
        </span>
        <br />
        <span>
          {" "}
          -Personal data should only be collected to fulfill a specific purpose
          and it should only be used for that purpose. Organizations must
          specify why they need personal data when they collect it.
        </span>
        <br />
        <span>
          -Personal data should be held no longer than necessary to fulfill its
          purpose.
        </span>
        <br />
        <span>
          {" "}
          -People covered by the GDPR have the right to access their own
          personal data. They can also request a copy of their data, and that
          their data be updated, deleted, restricted, or moved to another
          organization.
        </span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Why is GDPR important?{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        GDPR adds some new requirements regarding how companies should protect
        individuals&apos; personal data that they collect and process. It also
        raises the stakes for compliance by increasing enforcement and imposing
        greater fines for breach. Beyond these facts, it&apos;s simply the right
        thing to do. At direct promotion, we strongly believe that your data
        privacy is very important, and we already have solid security and
        privacy practices in place that go beyond the requirements of this new
        regulation.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Individual Data Subject&apos;s Rights - Data Access, Portability, and
        Deletion{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We are committed to helping our customers meet the data subject rights
        requirements of GDPR. direct promotion processes or stores all personal
        data in fully vetted, DPA compliant vendors. We do store all
        conversation and personal data for up to 6 years unless your account is
        deleted. In which case, we dispose of all data in accordance with our
        Terms of Service and Privacy Policy, but we will not hold it longer than
        60 days. We are aware that if you are working with EU customers, you
        need to be able to provide them with the ability to access, update,
        retrieve and remove personal data. We got you! We&apos;ve been set up as
        self-service from the start and have always given you access to your
        data and your customer’s data. Our customer support team is here for you
        to answer any questions you might have about working with the API.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        California Residents{" "}
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The California Consumer Privacy Act (CCPA) requires us to disclose
        categories of Personal Information we collect and how we use it, the
        categories of sources from whom we collect Personal Information, and the
        third parties with whom we share it, which we have explained above. We
        are also required to communicate information about the rights California
        residents have under California law. You may exercise the following
        rights:
        <span> -Right to Know and Access.</span>
        You may submit a verifiable request for information regarding the: (1)
        categories of Personal Information we collect, use, or share; (2)
        purposes for which categories of Personal Information are collected or
        used by us; (3) categories of sources from which we collect Personal
        Information; and (4) specific pieces of Personal Information we have
        collected about you.
        <br />
        <span>-Right to Equal Service.</span> We will not discriminate against
        you if you exercise your privacy rights.
        <br />
        <span>-Right to Delete.</span> You may submit a verifiable request to
        close your account and we will delete the Personal Information about you
        that we have collected.
        <br />
        <span>
          -Request that a business that sells a consumer&apos;s personal data,
          not sell the consumer&apos;s personal data.
          <br />
        </span>{" "}
        <br />
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us. We do not sell
        the Personal Information of our users. For more information about these
        rights, please contact us.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Contact Us</h4>
      <p className="text-sm text-gray-400 mb-5">
        Don&apos;t hesitate to contact us if you have any questions.
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via Phone Number: 7792188306{" "}
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via this Link: support@directpromotion.online
      </p>
    </div>
  );
};

export default Terms;
