const CookiesPolicy = () => {
  return (
    <div className="max-w-7xl my-10 mx-auto max-2xl:mx-5">
      <h1 className="max-sm:text-lg max-md:text-2xl max-lg:text-4xl text-5xl font-bold text-center mb-10">
        Cookies <span className="text-[#FB6D11]">Policy</span>
      </h1>
      <p className="text-sm text-gray-400 mb-5">Updated at 2022-05-01</p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Definitions and key terms
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        To help explain things as clearly as possible in this Cookie Policy,
        every time any of these terms are referenced, are strictly defined as:
        <span>-Cookie</span>: a small amount of data generated by a website and
        saved by your web browser. It is used to identify your browser, provide
        analytics, remember information about you such as your language
        preference or login information.
        <br />
        <span>-Company</span>: when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Direct Promotion, which is responsible for your
        information under this Cookie Policy.
        <br />
        <span>-Device</span>: any internet-connected device such as a phone,
        tablet, computer, or any other device that can be used to visit Direct
        Promotion and use the services.
        <br />
        <span>-Personal</span> Data: Any information that directly, indirectly,
        or in connection with other information — including a personal
        identification number — allows for the identification or identifiability
        of a natural person.
        <br />
        <span>-Service</span>: refers to the service provided by Direct
        Promotion as described in the relative terms (if available) and on this
        platform.
        <br />
        <span>-Third-party service</span>: refers to advertisers, contest
        sponsors, promotional and marketing partners, and others who provide our
        content or whose products or services we think may interest you. <br />
        <span>-Website</span>: Direct Promotion’s&quot; site, which can be
        accessed via this URL: https://www.directpromotion.online/ -You: a
        person or entity that is registered with Direct Promotion to use the
        Services.
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Introduction</h4>
      <p className="text-sm text-gray-400 mb-5">
        This Cookie Policy explains how Direct Promotion and its affiliates
        (collectively &quot;Direct Promotion&quot;, &quot;we&quot;,
        &quot;us&quot;, and &quot;ours&quot;), use cookies and similar
        technologies to recognize you when you visit our website, including
        without limitation https://www.directpromotion.online/ and any related
        URLs, mobile or localized versions and related domains/subdomains
        (&quot;Websites&quot;). It explains what these technologies are and why
        we use them, as well as the choices for how to control them.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What is a cookie?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        A cookie is a small text file that is stored on your computer or another
        internet-connected device to identify your browser, provide analytics,
        remember information about you such as your language preference or login
        information. They&apos;re completely safe and can&apos;t be used to run
        programs or deliver viruses to your device.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Why do we use cookies?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We use first party and/or third-party cookies on our website for various
        purposes such as:
        <br />
        <span>
          -To facilitate the operation and functionality of our website.{" "}
        </span>{" "}
        <br />
        <span>
          -To improve your experience of our website and make navigating around
          it quicker and easier.
        </span>{" "}
        <br />
        <span>
          -To allow us to make a bespoke user experience for you and for us to
          understand what is useful or of interest to you.
        </span>{" "}
        <br />
        <span>
          {" "}
          -To analyze how our website is used and how best we can customize it.
        </span>
        <br />
        <span>
          {" "}
          -To identify prospects and personalize marketing and sales
          interactions with them
        </span>
        <br />
        <span>
          -To facilitate the tailoring of online advertising to your interests.
        </span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        What type of cookies does Direct Promotion use?
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Cookies can either be session cookies or persistent cookies. A session
        cookie expires automatically when you close your browser. A persistent
        cookie will remain until it expires, or you delete your cookies.
        Expiration dates are set in the cookies themselves; some may expire
        after a few minutes while others may expire after multiple years.
        Cookies placed by the website you’re visiting are called “first party
        cookies”. Strictly Necessary cookies are necessary for our website to
        function and cannot be switched off in our systems. They are essential
        to enable you to navigate around the website and use its features. If
        you remove or disable these cookies, we cannot guarantee that you will
        be able to use our website. We use the following types of cookies in our
        website: <br />
        <span>Essential Cookies</span> We use essential cookies to make our
        website work. These cookies are strictly necessary to enable core
        functionality such as security, network management, your cookie
        preferences, and accessibility. Without them, you wouldn&apos;t be able
        to use basic services. You may disable these by changing your browser
        settings, but this may affect how the Websites function. <br />
        <span>Marketing Cookies</span> These account-based marketing cookies
        enable us to identify prospects and personalize sales and marketing
        interactions with them. <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Marketing Cookies
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Most browsers allow you to control cookies through their
        &apos;settings&apos; preferences. However, if you limit the ability of
        websites to set cookies, you may worsen your overall user experience,
        since it will no longer be personalized to you. It may also stop you
        from saving customized settings like login information. Browser
        manufacturers provide help pages relating to cookie management in their
        products. Browser manufacturers provide help pages relating to cookie
        management in their products. Please see below for more information.{" "}
        <br />
        <span>-Google Chrome</span>
        <br />
        <span> -Internet Explorer</span>
        <br />
        <span> -Mozilla Firefox </span>
        <br />
        <span> -Safari (Desktop)</span>
        <br />
        <span> -Safari (Mobile)</span>
        <br />
        <span>-Android Browser</span>
        <br />
        <span>-Opera</span>
        <br />
        <span>-Opera Mobile</span>
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Blocking and disabling cookies and similar technologies
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Wherever you&apos;re located you may also set your browser to block
        cookies and similar technologies, but this action may block our
        essential cookies and prevent our website from functioning properly, and
        you may not be able to fully utilize all its features and services. You
        should also be aware that you may also lose some saved information
        (e.g., saved login details, site preferences) if you block cookies on
        your browser. Different browsers make different controls available to
        you. Disabling a cookie or category of cookie does not delete the cookie
        from your browser, you will need to do this yourself from within your
        browser, you should visit your browser&apos;s help menu for more
        information.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Changes To Our Cookie Policy
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        We may change our Service and policies, and we may need to make changes
        to this Cookie Policy so that it accurately reflects our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Cookie
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Cookie Policy. If you do not want to agree to this or any
        updated Cookie Policy, you can delete your account.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent</h4>
      <p className="text-sm text-gray-400 mb-5">
        By using our website, registering an account, or making a purchase, you
        hereby consent to our Cookie Policy and agree to its terms.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Contact Us</h4>
      <p className="text-sm text-gray-400 mb-5">
        Don&apos;t hesitate to contact us if you have any questions regarding
        our Cookie Policy.
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via Email: support@directpromotion.online
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via Phone Number: +1 779-218-8306{" "}
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via this Link: https://www.directpromotion.online/
      </p>
    </div>
  );
};

export default CookiesPolicy;
