const Disclaimer = () => {
  return (
    <div className="max-w-7xl my-10 mx-auto max-2xl:mx-5">
      <h1 className="max-sm:text-lg max-md:text-2xl max-lg:text-4xl text-5xl font-bold text-center mb-10 text-[#FB6D11]">
        Disclaimer
      </h1>
      <p className="text-sm text-gray-400 mb-5">Updated at 2022-05-01</p>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion hereby grants you access to
        https://www.directpromotion.online/ (“the Website”) and invites you to
        purchase the services offered here.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Definitions and key terms
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        To help explain things as clearly as possible in this Disclaimer, every
        time any of these terms are referenced, are strictly defined as:
        <br />
        <span> -Cookie</span> : a small amount of data generated by a website
        and saved by your web browser. It is used to identify your browser,
        provide analytics, remember information about you such as your language
        preference or login information.
        <br />
        <span> -Company</span>: when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Direct Promotion that is responsible for your
        information under this Disclaimer. -Service: refers to the service
        provided by Direct Promotion as described in the relative terms (if
        available) and on this platform.
        <br />
        <span> -Website</span>: Direct Promotion’s&quot; site, which can be
        accessed via this URL: https://www.directpromotion.online/ -You: a
        person or entity that is registered with Direct Promotion to use the
        Services.
        <br />
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Limited liability
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion endeavors to update and/or supplement the content of
        the website on a regular basis. Despite our care and attention, content
        may be incomplete and/or incorrect. The materials offered on the website
        are offered without any form of guarantee or claim to their correctness.
        These materials can be changed at any time without prior notice from
        Direct Promotion. Particularly, all prices on the website are stated
        subject to typing and programming errors. No liability is assumed for
        the implications of such errors. No agreement is concluded based on such
        errors. Direct Promotion shall not bear any liability for hyperlinks to
        websites or services of third parties included on the website. From our
        website, you can visit other websites by following hyperlinks to such
        external sites. While we strive to provide only quality links to useful
        and ethical websites, we have no control over the content and nature of
        these sites. These links to other websites do not imply a recommendation
        for all the content found on these sites. Site owners and content may
        change without notice and may occur before we have the opportunity to
        remove a link that may have gone ‘bad’. Please also be aware that when
        you leave our website, other sites may have different privacy policies
        and terms that are beyond our control. Please be sure to check the
        Privacy Policies of these sites as well as their &quot;Terms of
        Service&quot; before engaging in any business or uploading any
        information.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Links to Other Websites Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        This Disclaimer applies only to the Services. The Services may contain
        links to other websites not operated or controlled by Direct Promotion.
        We are not responsible for the content, accuracy or opinions expressed
        in such websites, and such websites are not investigated, monitored, or
        checked for accuracy or completeness by us. Please remember that when
        you use a link to go from the Services to another website, our Privacy
        Policy is no longer in effect. You’re browsing and interacting on any
        other website, including those that have a link on our platform, is
        subject to that website’s own rules and policies. Third parties may use
        their own cookies or other methods to collect information about you. If
        You click on third-party link, you will be directed to that third
        party&apos;s site. We strongly advise You to review the Privacy Policy
        and Terms of every site You visit. We have no control over and assume no
        responsibility for the content, privacy policies or practices of any
        third-party sites or services.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Errors and Omissions Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion is not responsible for any content, code, or any other
        imprecision. Direct Promotion does not provide warranties or guarantees.
        In no event shall Direct Promotion be liable for any special, direct,
        indirect, consequential, or incidental damages or any damages
        whatsoever, whether in an action of contract, negligence, or another
        tort, arising out of or in connection with the use of the Service or the
        contents of the Service. Direct Promotion reserves the right to make
        additions, deletions, or modifications to the content of the Service at
        any time without prior notice.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        General Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The Direct Promotion Service and its contents are provided &quot;as
        is&quot; and &quot;as available&quot; without any warranty or
        representations of any kind, whether express or implied. Direct
        Promotion is a distributor and not a publisher of the content supplied
        by third parties; as such, Direct Promotion exercises no editorial
        control over such content and makes no warranty or representation as to
        the accuracy, reliability, or currency of any information, content,
        service or merchandise provided through or accessible via the Direct
        Promotion Service. Without limiting the foregoing, Direct Promotion
        specifically disclaims all warranties and representations in any content
        transmitted on or in connection with the Direct Promotion Service or on
        sites that may appear as links on the Direct Promotion Service, or in
        the products provided as a part of, or otherwise in connection with, the
        Direct Promotion Service, including without limitation any warranties of
        merchantability, fitness for a particular purpose or non-infringement of
        third party rights. No oral advice or written information given by
        Direct Promotion or any of its affiliates, employees, officers,
        directors, agents, or the like will create a warranty. Price and
        availability information is subject to change without notice. Without
        limiting the foregoing, Direct Promotion does not warrant that the
        Direct Promotion Service will be uninterrupted, uncorrupted, timely, or
        error-free.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Copyright Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        All intellectual property rights concerning these materials are vested
        in Direct Promotion. Copying, distribution and any other use of these
        materials is not permitted without the written permission of Direct
        Promotion, except and only to the extent otherwise provided in
        regulations of mandatory law (such as the right to quote), unless
        otherwise stated for certain materials.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Affiliate Links Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Direct Promotion has affiliate links and in this section of the
        Disclaimer we will address how we use those affiliate links from other
        websites/companies and products. These “affiliate links” are specific
        URLs that contain the affiliate&apos;s ID or username. In compliance
        with the FTC guidelines, please assume the following about links and
        posts on this site: -Any/all the links on Direct Promotion are affiliate
        links of which we receive a small commission from sales of certain
        items, but the price is the same for you. As Direct Promotion has grown,
        so have costs associated with running and maintaining it, and affiliate
        links are a way we help offset these costs. -If we post an affiliate
        link to a product, it is something that we personally use, support and
        would recommend without an affiliate link. -Unless otherwise noted, all
        reviews are of items we have purchased, and we are not paid or
        compensated in any way.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Health Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The information on this website such as text, graphics, images, and
        other materials created by Direct Promotion or obtained from Direct
        promotion’s&quot; licensors, and other materials contained on Direct
        Promotion (collectively, Contents”) is intended solely for informational
        purposes and may not be used as a substitute for professional advice
        and/or information, as circumstances will vary from person to person.
        You should not act or rely upon this information without seeking
        professional advice. Do not attempt any of the suggested actions,
        solutions, remedies, or instructions found on this website without first
        consulting with a qualified professional. The materials are not intended
        to be, nor do they constitute actionable professional advice.
        Transmissions of this information are not intended to create a
        professional-client relationship between Level Up Enterprises and you.
        The owners, editors, contributors, administrators, and other staff of
        Level Up Enterprises are not qualified professional, and are simply
        aggregating information found online for informational purposes only. If
        you think you may have a medical emergency, call your doctor or 911
        immediately. Direct Promotion does not recommend or endorse any specific
        tests, physicians, products, procedures, opinions, or other information
        that may be mentioned on the website. Reliance on any information
        provided by Direct Promotion, Direct Promotion employees, others
        appearing on the website at the invitation of Direct Promotion, or other
        visitors to the website is solely at your own risk.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Legal Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        The materials, any comments or information provided by Direct Promotion
        are for educational purposes only and nothing conveyed or provided
        should be considered legal, accounting or tax advice. You are
        responsible for whatever you may do with the information you obtain from
        Direct Promotion. As such, by visiting and using this website you
        acknowledge and agree that you have been assessed by a qualified law
        expert (i.e your attorney) who has given you consent to take part in any
        legal activity. Please contact your own attorney, accountant or tax
        professional with any specific questions you have related to the
        information provided that are of legal, accounting or tax nature.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Educational Disclosure
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Any information provided by Direct Promotion is for educational purposes
        only and is not to be interpreted as a recommendation for a specific
        treatment plan, product, or course of action. Direct Promotion is a
        distributor and not a publisher of the content supplied by third
        parties; as such, Direct Promotion exercises no editorial control over
        such content and makes no warranty or representation as to the accuracy,
        reliability or currency of any information or educational content
        provided through or accessible via Direct Promotion. Without limiting
        the foregoing, Direct Promotion specifically disclaims all warranties
        and representations in any content transmitted on or in connection with
        Direct Promotion or on sites that may appear as links on Direct
        Promotion, or in the products provided as a part of, or otherwise in
        connection with, the Direct Promotion. No oral advice or written
        information given by Direct Promotion or any of its affiliates,
        employees, officers, directors, agents, or the like will create a
        warranty.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Your Consent</h4>
      <p className="text-sm text-gray-400 mb-5">
        We&apos;ve updated our Disclaimer to provide you with complete
        transparency into what is being set when you visit our site and how
        it&apos;s being used. By using our website, registering an account, or
        making a purchase, you hereby consent to our Disclaimer and agree to its
        terms.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">
        Changes To Our Disclaimer
      </h4>
      <p className="text-sm text-gray-400 mb-5">
        Should we update, amend or make any changes to this document so that
        they accurately reflect our Service and policy?. Unless otherwise
        required by law, those changes will be prominently posted here. Then, if
        you continue to use the Service, you will be bound by the updated
        Disclaimer. If you do not want to agree to this or any updated
        Disclaimer, you can delete your account.
      </p>

      <h4 className="text-xl max-md:text-lg text-black mb-2">Contact Us</h4>
      <p className="text-sm text-gray-400 mb-5">
        Don&apos;t hesitate to contact us if you have any questions regarding
        this Disclaimer.
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via Email: support@directpromotion.online
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via Phone Number: +1 779-218-8306{" "}
      </p>
      <p className="text-sm text-gray-400 mb-5">
        -Via this Link: https://www.directpromotion.online/
      </p>
    </div>
  );
};

export default Disclaimer;
